### ISSUE TITLE
Add request throttling for autocomplete

### ISSUE THREAD

**Issue by ecgreb** [pelias/pelias-android-sdk#28]

**Comment by missinglink** [comment]
ref: https://mapzen.com/documentation/search/autocomplete/#user-experience-guidelines

**Comment by sarahlensing** [comment]
probably related...i just got this crash:

```
06-13 10:50:43.247 18032-18032/com.mapzen.erasermap E/PeliasSearchView: Unable to fetch autocomplete results
                                                                        retrofit.RetrofitError: 429 Too Many Requests
                                                                            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
                                                                            at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
                                                                            at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
                                                                            at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at retrofit.Platform$Android$2$1.run(Platform.java:142)
                                                                            at java.lang.Thread.run(Thread.java:818)
```

**Comment by ecgreb** [comment]
I am getting this crash even more now when testing the Places API for Android since it is hammering the autocomplete endpoint.

Now that we have upgraded to Retrofit2/OkHttp3 we should address this sooner than later.
